-- 001_InitialSchema.sql
-- Custom SQL Migration Script for SalesCRM

CREATE TABLE IF NOT EXISTS "__SqlMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "AppliedOn" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PK___SqlMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE IF NOT EXISTS "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Description" text,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Branches" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Address" text,
    "Phone" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Branches" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Customers" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Phone" text,
    "Email" text,
    "Address" text,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Customers" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" uuid NOT NULL,
    "Code" text NOT NULL,
    "Barcode" text,
    "Name" text NOT NULL,
    "Description" text,
    "SellingPrice" numeric NOT NULL,
    "ImportPrice" numeric NOT NULL,
    "ImageUrl" text,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUsers" (
    "Id" uuid NOT NULL,
    "FullName" text NOT NULL,
    "BranchId" uuid,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id")
);

CREATE TABLE IF NOT EXISTS "Locations" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "LocationCode" text NOT NULL,
    "Description" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Locations_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "StockTransfers" (
    "Id" uuid NOT NULL,
    "TransferCode" text NOT NULL,
    "FromBranchId" uuid NOT NULL,
    "ToBranchId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_StockTransfers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockTransfers_Branches_FromBranchId" FOREIGN KEY ("FromBranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StockTransfers_Branches_ToBranchId" FOREIGN KEY ("ToBranchId") REFERENCES "Branches" ("Id") ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS "BranchInventories" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "MinimumStockLevel" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_BranchInventories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BranchInventories_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BranchInventories_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ProductBatches" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "BatchCode" text NOT NULL,
    "ExpiryDate" timestamp with time zone NOT NULL,
    "ManufacturedDate" timestamp with time zone,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_ProductBatches" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductBatches_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductBatches_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Shifts" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone,
    "StartCash" numeric NOT NULL,
    "EndCashCounted" numeric,
    "TotalSalesCash" numeric NOT NULL,
    "TotalSalesMomo" numeric NOT NULL,
    "TotalSalesVNPay" numeric NOT NULL,
    "TotalSalesBank" numeric NOT NULL,
    "Status" text NOT NULL,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Shifts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Shifts_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Shifts_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "InventoryTransactions" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductBatchId" uuid,
    "Quantity" integer NOT NULL,
    "Type" integer NOT NULL,
    "ReferenceCode" text,
    "Notes" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_InventoryTransactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_InventoryTransactions_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_InventoryTransactions_ProductBatches_ProductBatchId" FOREIGN KEY ("ProductBatchId") REFERENCES "ProductBatches" ("Id"),
    CONSTRAINT "FK_InventoryTransactions_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ProductLocations" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "LocationId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductBatchId" uuid,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_ProductLocations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ProductLocations_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProductLocations_ProductBatches_ProductBatchId" FOREIGN KEY ("ProductBatchId") REFERENCES "ProductBatches" ("Id"),
    CONSTRAINT "FK_ProductLocations_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "StockTransferDetails" (
    "Id" uuid NOT NULL,
    "StockTransferId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductBatchId" uuid,
    "Quantity" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_StockTransferDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StockTransferDetails_ProductBatches_ProductBatchId" FOREIGN KEY ("ProductBatchId") REFERENCES "ProductBatches" ("Id"),
    CONSTRAINT "FK_StockTransferDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StockTransferDetails_StockTransfers_StockTransferId" FOREIGN KEY ("StockTransferId") REFERENCES "StockTransfers" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "OrderCode" text NOT NULL,
    "CustomerId" uuid,
    "TotalAmount" numeric NOT NULL,
    "Discount" numeric NOT NULL,
    "FinalAmount" numeric NOT NULL,
    "Status" integer NOT NULL,
    "ShiftId" uuid,
    "CouponCode" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Orders_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id"),
    CONSTRAINT "FK_Orders_Shifts_ShiftId" FOREIGN KEY ("ShiftId") REFERENCES "Shifts" ("Id")
);

CREATE TABLE IF NOT EXISTS "OrderDetails" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "ProductBatchId" uuid,
    "Quantity" integer NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_OrderDetails" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_OrderDetails_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_OrderDetails_ProductBatches_ProductBatchId" FOREIGN KEY ("ProductBatchId") REFERENCES "ProductBatches" ("Id"),
    CONSTRAINT "FK_OrderDetails_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Payments" (
    "Id" uuid NOT NULL,
    "OrderId" uuid NOT NULL,
    "PaymentMethod" integer NOT NULL,
    "Amount" numeric NOT NULL,
    "Status" integer NOT NULL,
    "TransactionNo" text,
    "PaymentPayload" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ReturnOrders" (
    "Id" uuid NOT NULL,
    "BranchId" uuid NOT NULL,
    "OriginalOrderId" uuid NOT NULL,
    "ReturnCode" text NOT NULL,
    "RefundAmount" numeric NOT NULL,
    "RefundMethod" text NOT NULL,
    "Reason" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_ReturnOrders" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReturnOrders_Branches_BranchId" FOREIGN KEY ("BranchId") REFERENCES "Branches" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReturnOrders_Orders_OriginalOrderId" FOREIGN KEY ("OriginalOrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ReturnOrderItems" (
    "Id" uuid NOT NULL,
    "ReturnOrderId" uuid NOT NULL,
    "ProductId" uuid NOT NULL,
    "Quantity" integer NOT NULL,
    "RefundPrice" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModifiedAt" timestamp with time zone,
    "LastModifiedBy" text,
    CONSTRAINT "PK_ReturnOrderItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReturnOrderItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReturnOrderItems_ReturnOrders_ReturnOrderId" FOREIGN KEY ("ReturnOrderId") REFERENCES "ReturnOrders" ("Id") ON DELETE CASCADE
);

-- Indexes

CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
CREATE INDEX IF NOT EXISTS "IX_AspNetUsers_BranchId" ON "AspNetUsers" ("BranchId");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Products_Code" ON "Products" ("Code");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_BranchInventories_BranchId_ProductId" ON "BranchInventories" ("BranchId", "ProductId");
CREATE INDEX IF NOT EXISTS "IX_BranchInventories_ProductId" ON "BranchInventories" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_InventoryTransactions_BranchId" ON "InventoryTransactions" ("BranchId");
CREATE INDEX IF NOT EXISTS "IX_InventoryTransactions_ProductBatchId" ON "InventoryTransactions" ("ProductBatchId");
CREATE INDEX IF NOT EXISTS "IX_InventoryTransactions_ProductId" ON "InventoryTransactions" ("ProductId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Locations_BranchId_LocationCode" ON "Locations" ("BranchId", "LocationCode");
CREATE INDEX IF NOT EXISTS "IX_OrderDetails_OrderId" ON "OrderDetails" ("OrderId");
CREATE INDEX IF NOT EXISTS "IX_OrderDetails_ProductBatchId" ON "OrderDetails" ("ProductBatchId");
CREATE INDEX IF NOT EXISTS "IX_OrderDetails_ProductId" ON "OrderDetails" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_Orders_BranchId" ON "Orders" ("BranchId");
CREATE INDEX IF NOT EXISTS "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
CREATE INDEX IF NOT EXISTS "IX_Orders_ShiftId" ON "Orders" ("ShiftId");
CREATE INDEX IF NOT EXISTS "IX_Payments_OrderId" ON "Payments" ("OrderId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductBatches_BranchId_ProductId_BatchCode" ON "ProductBatches" ("BranchId", "ProductId", "BatchCode");
CREATE INDEX IF NOT EXISTS "IX_ProductBatches_ProductId" ON "ProductBatches" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_ProductLocations_LocationId" ON "ProductLocations" ("LocationId");
CREATE INDEX IF NOT EXISTS "IX_ProductLocations_ProductBatchId" ON "ProductLocations" ("ProductBatchId");
CREATE INDEX IF NOT EXISTS "IX_ProductLocations_ProductId" ON "ProductLocations" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_ReturnOrderItems_ProductId" ON "ReturnOrderItems" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_ReturnOrderItems_ReturnOrderId" ON "ReturnOrderItems" ("ReturnOrderId");
CREATE INDEX IF NOT EXISTS "IX_ReturnOrders_BranchId" ON "ReturnOrders" ("BranchId");
CREATE INDEX IF NOT EXISTS "IX_ReturnOrders_OriginalOrderId" ON "ReturnOrders" ("OriginalOrderId");
CREATE INDEX IF NOT EXISTS "IX_Shifts_BranchId" ON "Shifts" ("BranchId");
CREATE INDEX IF NOT EXISTS "IX_Shifts_UserId" ON "Shifts" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_StockTransferDetails_ProductBatchId" ON "StockTransferDetails" ("ProductBatchId");
CREATE INDEX IF NOT EXISTS "IX_StockTransferDetails_ProductId" ON "StockTransferDetails" ("ProductId");
CREATE INDEX IF NOT EXISTS "IX_StockTransferDetails_StockTransferId" ON "StockTransferDetails" ("StockTransferId");
CREATE INDEX IF NOT EXISTS "IX_StockTransfers_FromBranchId" ON "StockTransfers" ("FromBranchId");
CREATE INDEX IF NOT EXISTS "IX_StockTransfers_ToBranchId" ON "StockTransfers" ("ToBranchId");

COMMIT;
