import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { useAuthStore } from '../../store/useAuthStore';
import { 
  Search, 
  UserPlus, 
  Phone, 
  Mail, 
  Award, 
  History, 
  Calendar,
  X,
  User,
  Ticket,
  Copy,
  CheckCircle,
  Download
} from 'lucide-react';
import axios from 'axios';
import { API_BASE_URL } from '../../config';
import './CRM.css';

interface Customer {
  id: string;
  fullName: string;
  phoneNumber: string;
  email?: string;
  loyaltyPoints: number;
  ordersCount: number;
}

interface PurchaseHistory {
  orderCode: string;
  dateStr: string;
  totalAmount: number;
  pointsEarned: number;
}

export const CRM: React.FC = () => {
  const { t } = useTranslation();
  const { token } = useAuthStore();
  const [searchTerm, setSearchTerm] = useState('');
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [selectedCustomer, setSelectedCustomer] = useState<Customer | null>(null);
  const [history, setHistory] = useState<PurchaseHistory[]>([]);
  const [loading, setLoading] = useState(false);

  // Vouchers generated by customer id
  const [customerVouchers, setCustomerVouchers] = useState<{[key: string]: string[]}>({});
  const [copiedCode, setCopiedCode] = useState<string | null>(null);

  // Form state
  const [isAddOpen, setIsAddOpen] = useState(false);
  const [newFullName, setNewFullName] = useState('');
  const [newPhone, setNewPhone] = useState('');
  const [newEmail, setNewEmail] = useState('');

  // Status message feedback
  const [successMsg, setSuccessMsg] = useState<string | null>(null);

  const fetchCustomers = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API_BASE_URL}/api/customers`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.data.isSuccess) {
        const items = Array.isArray(res.data.data) ? res.data.data : res.data.data.items;
        setCustomers(items || []);
      }
    } catch (err) {
      console.warn("Failed live customer fetch. Mocking CRM data.", err);
      // Premium Mock CRM Data
      const mockList = [
        { id: 'c1', fullName: 'Nguyễn Văn A', phoneNumber: '0912345678', email: 'anv@gmail.com', loyaltyPoints: 350, ordersCount: 12 },
        { id: 'c2', fullName: 'Trần Thị B', phoneNumber: '0987654321', email: 'btt@yahoo.com', loyaltyPoints: 120, ordersCount: 5 },
        { id: 'c3', fullName: 'Lê Văn C', phoneNumber: '0905112233', email: 'clevan@outlook.com', loyaltyPoints: 850, ordersCount: 24 },
        { id: 'c4', fullName: 'Phạm Minh D', phoneNumber: '0938445566', email: 'minhpham@gmail.com', loyaltyPoints: 45, ordersCount: 2 }
      ];
      setCustomers(mockList);
      if (!selectedCustomer) {
        setSelectedCustomer(mockList[0]);
      }
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCustomers();
  }, [token]);

  // Load customer purchase history
  useEffect(() => {
    if (!selectedCustomer) return;

    const fetchHistory = async () => {
      try {
        const res = await axios.get(`${API_BASE_URL}/api/customers/${selectedCustomer.id}/history`, {
          headers: { Authorization: `Bearer ${token}` }
        });
        if (res.data.isSuccess) setHistory(res.data.data);
      } catch (err) {
        // Mock purchase history
        setHistory([
          { orderCode: 'ORD90215', dateStr: '2026-06-02 10:15', totalAmount: 185000, pointsEarned: 18 },
          { orderCode: 'ORD88421', dateStr: '2026-05-28 16:45', totalAmount: 420000, pointsEarned: 42 },
          { orderCode: 'ORD71050', dateStr: '2026-05-15 08:30', totalAmount: 95000, pointsEarned: 9 }
        ]);
      }
    };
    fetchHistory();
  }, [selectedCustomer, token]);

  const handleAddSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newFullName || !newPhone) {
      alert("Họ tên và số điện thoại là bắt buộc.");
      return;
    }

    const payload = {
      fullName: newFullName,
      phoneNumber: newPhone,
      email: newEmail
    };

    try {
      const res = await axios.post(`${API_BASE_URL}/api/customers`, payload, {
        headers: { Authorization: `Bearer ${token}` }
      });
      if (res.data.isSuccess) {
        setSuccessMsg(t('crm.add_customer') + " thành công!");
        setIsAddOpen(false);
        setNewFullName('');
        setNewPhone('');
        setNewEmail('');
        fetchCustomers();
      }
    } catch (err) {
      console.warn("Adding offline mockup customer.");
      const mockNew: Customer = {
        id: 'c_new_' + Date.now(),
        fullName: newFullName,
        phoneNumber: newPhone,
        email: newEmail || undefined,
        loyaltyPoints: 0,
        ordersCount: 0
      };
      setCustomers([mockNew, ...customers]);
      setSelectedCustomer(mockNew);
      setSuccessMsg(t('crm.add_customer') + " thành công [Offline Mode]!");
      setIsAddOpen(false);
      setNewFullName('');
      setNewPhone('');
      setNewEmail('');
    }

    setTimeout(() => setSuccessMsg(null), 3000);
  };

  const handleRedeemPoints = (pointsToRedeem: number, voucherText: string) => {
    if (!selectedCustomer) return;
    if (selectedCustomer.loyaltyPoints < pointsToRedeem) {
      alert("Không đủ điểm tích lũy để thực hiện giao dịch này.");
      return;
    }

    // Deduct points locally
    const updated = {
      ...selectedCustomer,
      loyaltyPoints: selectedCustomer.loyaltyPoints - pointsToRedeem
    };

    setCustomers(customers.map(c => c.id === selectedCustomer.id ? updated : c));
    setSelectedCustomer(updated);

    // Generate random coupon code
    const code = `VIP${voucherText}_` + Math.floor(1000 + Math.random() * 9000);
    const existing = customerVouchers[selectedCustomer.id] || [];
    setCustomerVouchers({
      ...customerVouchers,
      [selectedCustomer.id]: [...existing, code]
    });

    setSuccessMsg(`Quy đổi thành công! Đã cấp Voucher: ${code}`);
    setTimeout(() => setSuccessMsg(null), 4000);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCode(text);
    setTimeout(() => setCopiedCode(null), 2000);
  };

  const getVipBadge = (points: number) => {
    if (points >= 600) return { name: t('crm.badge_diamond'), class: 'badge-diamond' };
    if (points >= 300) return { name: t('crm.badge_gold'), class: 'badge-gold' };
    if (points >= 100) return { name: t('crm.badge_silver'), class: 'badge-silver' };
    return { name: t('crm.badge_bronze'), class: 'badge-bronze' };
  };

  const filteredCustomers = customers.filter(c => 
    c.fullName.toLowerCase().includes(searchTerm.toLowerCase()) ||
    c.phoneNumber.includes(searchTerm)
  );

  const formatCurrency = (val: number) => {
    return new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' }).format(val);
  };

  const exportCustomersToCSV = () => {
    if (customers.length === 0) return;
    const headers = ['Mã khách hàng', 'Họ tên', 'Số điện thoại', 'Email', 'Điểm tích lũy', 'Số đơn hàng'];
    const csvRows = [
      headers.join(','),
      ...customers.map(c => [
        c.id,
        `"${c.fullName.replace(/"/g, '""')}"`,
        c.phoneNumber,
        c.email || '',
        c.loyaltyPoints,
        c.ordersCount
      ].join(','))
    ];
    const csvContent = "\uFEFF" + csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `danh_sach_khach_hang_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="crm-container">
      {/* Header Row */}
      <div className="crm-header-row">
        <div>
          <h1 className="crm-title glow-text">{t('crm.title')}</h1>
          <p className="crm-subtitle">{t('crm.subtitle_description')}</p>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button className="add-cust-btn" onClick={exportCustomersToCSV} style={{ background: 'var(--card-inset)', borderColor: 'var(--card-border)', color: 'var(--text-primary)' }}>
            <Download size={18} />
            <span>{t('crm.export_csv')}</span>
          </button>
          <button className="add-cust-btn" onClick={() => setIsAddOpen(true)}>
            <UserPlus size={18} />
            <span>{t('crm.add_customer')}</span>
          </button>
        </div>
      </div>

      {successMsg && <div className="feedback-banner success-banner">{successMsg}</div>}

      <div className="crm-workspace">
        {/* Customer Search List */}
        <div className="crm-sidebar-list glass-container">
          <div className="crm-search-bar">
            <Search className="search-icon" size={18} />
            <input 
              type="text" 
              placeholder={t('crm.search_placeholder', { defaultValue: 'Tìm theo tên hoặc số điện thoại...' })} 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="crm-search-input"
            />
          </div>

          <div className="customer-list">
            {loading ? (
              <div className="spinner-wrapper"><div className="spinner"></div></div>
            ) : filteredCustomers.length === 0 ? (
              <div className="empty-list">{t('common.no_data')}</div>
            ) : (
              filteredCustomers.map(c => {
                const badge = getVipBadge(c.loyaltyPoints);
                return (
                  <div 
                    key={c.id} 
                    className={`customer-item ${selectedCustomer?.id === c.id ? 'active' : ''}`}
                    onClick={() => setSelectedCustomer(c)}
                  >
                    <div className="cust-avatar">
                      <User size={16} />
                    </div>
                    <div className="cust-mini-info">
                      <span className="cust-name">{c.fullName}</span>
                      <span className="cust-phone">{c.phoneNumber}</span>
                    </div>
                    <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px' }}>
                      <div className="cust-mini-points">
                        <Award size={14} className="points-award-icon" />
                        <span>{c.loyaltyPoints}</span>
                      </div>
                      <span className={`vip-rank-small-badge ${badge.class}`}>{badge.name}</span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        {/* Selected Customer Details */}
        <div className="crm-detail-view glass-container">
          {selectedCustomer ? (
            <div className="cust-detail-layout">
              {/* Profile Card header */}
              <div className="cust-profile-card">
                <div className="profile-main">
                  <div className="profile-avatar">
                    {selectedCustomer.fullName.charAt(0).toUpperCase()}
                  </div>
                  <div className="profile-text">
                    <h2>
                      {selectedCustomer.fullName}
                      <span className={`vip-badge-main ${getVipBadge(selectedCustomer.loyaltyPoints).class}`}>
                        {getVipBadge(selectedCustomer.loyaltyPoints).name}
                      </span>
                    </h2>
                    <span className="profile-id">ID: {selectedCustomer.id.substring(0, 8)}...</span>
                  </div>
                </div>

                <div className="profile-stats">
                  <div className="stat-box">
                    <Award size={20} className="stat-icon pts-icon" />
                    <span className="stat-val">{selectedCustomer.loyaltyPoints}</span>
                    <span className="stat-lbl">{t('crm.points')}</span>
                  </div>
                  <div className="stat-box">
                    <History size={20} className="stat-icon orders-count-icon" />
                    <span className="stat-val">{selectedCustomer.ordersCount}</span>
                    <span className="stat-lbl">{t('crm.orders_count')}</span>
                  </div>
                </div>
              </div>

              {/* Information & Contacts */}
              <div className="contact-details">
                <div className="contact-item">
                  <Phone size={18} />
                  <span>{selectedCustomer.phoneNumber}</span>
                </div>
                {selectedCustomer.email && (
                  <div className="contact-item">
                    <Mail size={18} />
                    <span>{selectedCustomer.email}</span>
                  </div>
                )}
              </div>

              {/* Points Redemption / Exchange Center */}
              <div className="redemption-center-container">
                <h3 className="section-title">
                  <Ticket size={16} />
                  <span>{t('crm.redemption_center')}</span>
                </h3>
                <div className="redemption-options-grid">
                  <div className="redeem-card">
                    <span className="reward-value">Voucher 50,000đ</span>
                    <span className="reward-cost">{t('crm.points_required')}: 50 {t('crm.points_unit')}</span>
                    <button 
                      className="redeem-btn" 
                      onClick={() => handleRedeemPoints(50, '50K')}
                      disabled={selectedCustomer.loyaltyPoints < 50}
                    >
                      {t('crm.btn_redeem')}
                    </button>
                  </div>

                  <div className="redeem-card">
                    <span className="reward-value">Voucher 100,000đ</span>
                    <span className="reward-cost">{t('crm.points_required')}: 100 {t('crm.points_unit')}</span>
                    <button 
                      className="redeem-btn" 
                      onClick={() => handleRedeemPoints(100, '100K')}
                      disabled={selectedCustomer.loyaltyPoints < 100}
                    >
                      {t('crm.btn_redeem')}
                    </button>
                  </div>

                  <div className="redeem-card">
                    <span className="reward-value">Voucher 300,000đ</span>
                    <span className="reward-cost">{t('crm.points_required')}: 300 {t('crm.points_unit')}</span>
                    <button 
                      className="redeem-btn" 
                      onClick={() => handleRedeemPoints(300, '300K')}
                      disabled={selectedCustomer.loyaltyPoints < 300}
                    >
                      {t('crm.btn_redeem')}
                    </button>
                  </div>
                </div>

                {/* Show available vouchers */}
                {(customerVouchers[selectedCustomer.id] || []).length > 0 && (
                  <div className="available-vouchers-list">
                    <h4>{t('crm.vouchers_list_title')}</h4>
                    <div className="vouchers-flex">
                      {(customerVouchers[selectedCustomer.id] || []).map((code, idx) => (
                        <div 
                          key={idx} 
                          className="voucher-item-badge" 
                          onClick={() => copyToClipboard(code)}
                          title="Click to copy voucher code"
                        >
                          <Ticket size={14} />
                          <span>{code}</span>
                          {copiedCode === code ? (
                            <CheckCircle size={12} style={{ color: '#34d399' }} />
                          ) : (
                            <Copy size={12} />
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Purchase History table */}
              <div className="history-section">
                <h3 className="section-title">
                  <History size={16} />
                  <span>{t('crm.history')}</span>
                </h3>
                <div className="history-list">
                  {history.length === 0 ? (
                    <div className="empty-history">{t('crm.empty_history')}</div>
                  ) : (
                    <div className="table-wrapper" style={{ overflowX: 'auto' }}>
                      <table className="history-table">
                        <thead>
                          <tr>
                            <th>{t('dashboard.th_code')}</th>
                            <th>{t('crm.purchase_date')}</th>
                            <th>{t('crm.total_invoice')}</th>
                            <th>{t('crm.points_earned')}</th>
                          </tr>
                        </thead>
                        <tbody>
                          {history.map((h, idx) => (
                            <tr key={idx}>
                              <td className="h-code">{h.orderCode}</td>
                              <td className="h-date"><Calendar size={12} /> {h.dateStr}</td>
                              <td className="h-amount">{formatCurrency(h.totalAmount)}</td>
                              <td className="h-pts">+{h.pointsEarned} pts</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  )}
                </div>
              </div>
            </div>
          ) : (
            <div className="no-cust-selected">
              <User size={64} className="no-cust-icon" />
              <p>{t('crm.no_customer_selected')}</p>
            </div>
          )}
        </div>
      </div>

      {/* Add Customer Modal */}
      {isAddOpen && (
        <div className="modal-overlay">
          <form className="modal-content glass-container" onSubmit={handleAddSubmit}>
            <div className="modal-header">
              <h3>{t('crm.add_customer')}</h3>
              <button type="button" className="modal-close" onClick={() => setIsAddOpen(false)}>
                <X size={20} />
              </button>
            </div>

            <div className="modal-body">
              <div className="form-group">
                <label className="form-label">{t('crm.fullname')} (*)</label>
                <input 
                  type="text" 
                  className="form-input" 
                  value={newFullName}
                  onChange={(e) => setNewFullName(e.target.value)}
                  placeholder={t('crm.placeholder_fullname')}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">{t('crm.phone')} (*)</label>
                <input 
                  type="text" 
                  className="form-input" 
                  value={newPhone}
                  onChange={(e) => setNewPhone(e.target.value)}
                  placeholder={t('crm.placeholder_phone')}
                  required
                />
              </div>

              <div className="form-group">
                <label className="form-label">{t('crm.email')}</label>
                <input 
                  type="email" 
                  className="form-input" 
                  value={newEmail}
                  onChange={(e) => setNewEmail(e.target.value)}
                  placeholder={t('crm.placeholder_email')}
                />
              </div>

              <button type="submit" className="modal-submit-btn">
                {t('crm.add_customer')}
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
};
